# Site settings
title: LSESU Christian Union
email: su.soc.christian.union@lse.ac.uk
description: "The LSESU Christian Union exists on campus at the London School of Economics to know Christ and make Him known. We meet every Thursday evening, as well as running other regular events."
url: "http://lsesucu.com"

# Build settings
markdown: kramdown
permalink: pretty
